{% set version = "1.11.3" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/archive/v{{ version }}.tar.gz
  sha256: 956afdeb9b5600e873326e410e9379684dac8f8f47ea569151a417984e7799cf
  patches:
    - numpy_distutils_ldflags.diff

build:
  number: 203
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - cython
    - toolchain
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  requires:
    - nose
  commands:
    - f2py -h
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
