{% set version = "1.9.3" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  sha256: c3b74d3b9da4ceb11f66abd21e117da8cf584b63a0efbd01a9b7e91b693fbbd6
  patches:
    - 11525.patch

build:
  number: 205
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite
  commands:
    - f2py -h

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - mariusvniekerk
